name: Simple Google Cloud Login

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Install Google Cloud CLI
      - name: Install Google Cloud CLI
        run: |
          echo "Installing Google Cloud SDK..."
          sudo apt-get update && sudo apt-get install -y google-cloud-sdk

      # Step 3: Authenticate Manually
      - name: Authenticate with gcloud
        run: gcloud auth login --no-launch-browser
        env:
          CLOUDSDK_CORE_PROJECT: devops-team-14-863342

      # Step 4: Deploy to Google Cloud
      - name: Deploy to Google Cloud
        run: gcloud app deploy --quiet
