name: Simple Google Cloud Deployment

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: "devops-team-14-863342" # Replace with your project ID
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Deploy application
      - name: Deploy to Google Cloud
        run: gcloud app deploy --quiet
