name: Simple Google Cloud Deployment

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.DEPLOY}}

      # Step 3: Install Google Cloud CLI
      - name: Install Google Cloud CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk

      # Step 4: Set Active Project
      - name: Set Active Project
        run: gcloud config set project devops-team-14-863342

      # Step 5: Deploy application
      - name: Deploy to Google Cloud
        run: gcloud app deploy --quiet
